### ISSUE TITLE
GLuaParser is dated

### ISSUE THREAD

**Issue by CaptainPRICE** [FPtje/GLuaParser#2]
![image](https://user-images.githubusercontent.com/9789070/67490694-e975e380-f673-11e9-8225-dc190f183d15.png)

**Comment by FPtje** [comment]
The cabal warnings are mere warnings. That part will work as it did before.

I just realised something, though. This repository is indeed dated. Looks like at some point I moved the code over to https://github.com/FPtje/GLuaFixer

Please try to compile that, it will compile both a library and the glualint executable. 

I'll change this repository to prevent further confusion. Thanks for telling me!
